# Generated by Django 4.2.7 on 2025-10-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название категории')),
                ('fbo_commission', models.DecimalField(decimal_places=2, help_text='Комиссия для схемы работы FBO (Fulfillment by Ozon) в процентах', max_digits=5, verbose_name='Комиссия FBO (%)')),
                ('fbs_commission', models.DecimalField(decimal_places=2, help_text='Комиссия для схемы работы FBS (Fulfillment by Seller) в процентах', max_digits=5, verbose_name='Комиссия FBS (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='categories__name_e3ad98_idx')],
            },
        ),
    ]
