# Generated by Django 4.2.7 on 2025-10-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_group',
            field=models.CharField(blank=True, db_index=True, help_text='Группа/категория товара (например: "Аксессуары", "VR-устройства и аксессуары")', max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Тип/название товара (например: "Шарф", "3D-очки")', max_length=255, unique=True, verbose_name='Тип товара'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_group'], name='categories__categor_47e9e5_idx'),
        ),
    ]
