# Generated by Django 4.2.7 on 2025-10-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_category_group_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Тип/название товара (например: "Шарф", "3D-очки")', max_length=255, verbose_name='Тип товара'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'category_group')},
        ),
    ]
