# Generated by Django 4.2.7 on 2025-10-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара (руб.)')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес товара (кг)')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Объем товара (л)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина (см)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота (см)')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Налог на прибыль (%)')),
                ('buyout_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Выкуп (%)')),
                ('delivery_time', models.IntegerField(verbose_name='Время доставки (часы)')),
                ('ad_costs_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доля рекламных расходов (%)')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость за 1 шт (руб.)')),
                ('other_costs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прочие затраты на 1 шт (руб.)')),
                ('monthly_sales', models.IntegerField(verbose_name='Количество продаж в месяц (шт)')),
                ('calculation_results', models.JSONField(help_text='Результаты расчета для FBO и FBS в формате JSON', verbose_name='Результаты расчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
